### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by keiz1213** [keiz1213/maru-batsu-quiz#41]

**Comment by keiz1213** [comment]
## ○✗クイズオンライン
- フロントエンドとバックエンドを分けて開発しようと思っています。
  - フロントエンド
    - Nuxt3
  - バックエンド
    - Rails7
- ユーザー認証はGithubログインのみです
## ER図
![marubatsu_drawio_-_diagrams_net](https://user-images.githubusercontent.com/72614612/227738918-5fd27bac-1c61-46ca-bf17-891ab9cc92fb.png)

## 説明
### users
- Githubログインのみ

| カラム | データ型 | 説明 |
|:-----------|:------------|:------------|
| id       | integer        | ユーザーのid         |
| uid     | string      | Githubのuser_id       |
| name       | string        | ユーザー名         |
| avatar_url         | string          | 画像url           |
| created_at       | datetime       | 登録日       |
| updated_at    | datetime     | 更新日      |

### games
- ユーザーは複数のゲームを作成することができる
- ユーザーは1ゲームの中に1つ以上の○✗クイズを登録できる
- ゲーム会場URLはゲームが作成されると自動で作成される
- ユーザーはゲームの生き残り人数を設定できる。1人なら最後の1人になるまでゲームを行う。

| カラム | データ型 | 説明 |
|:-----------|:------------|:------------|
| id       | integer        | ゲームのid         |
| user_id     | integer      | ゲームの作成者。作成者は自動的に出題者になる       |
| title       | string        | ゲームのタイトル         |
| description         | text          | ゲームの説明           |
| number_of_winner         | integer          | このゲームの生き残り人数           |
| room_url         | string          | このゲームの会場URL。このURLに参加者がアクセスしゲームを行う。           |
| created_at       | datetime       | 登録日       |
| updated_at    | datetime     | 更新日      |

### quizzes
- ○✗クイズは設問、正解、解説でワンセット

| カラム | データ型 | 説明 |
|:-----------|:------------|:------------|
| id       | integer        | ○✗クイズのid         |
| game_id     | integer      | このクイズが出題されるゲームのid      |
| question       | text        | クイズの設問         |
| correct_answer         | string          | クイズの正解(◯or✕)           |
| explanation         | text          | クイズの解説           |
| created_at       | datetime       | 登録日       |
| updated_at    | datetime     | 更新日      |

**Comment by kfukai23** [comment]
よさそうです！
