### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by keiz1213** [keiz1213/maru-batsu-quiz#42]

**Comment by keiz1213** [comment]
## ○✗クイズオンライン
- フロントエンドとバックエンドを分けて開発しようと思っています。
  - フロントエンド
    - Nuxt3
  - バックエンド
    - Rails7
- ユーザー認証はGithubログインのみです

## リソース設計
### フロントエンド
| URL | 説明 |
|:-----------|:------------|
|  /      |  ログイン前welcomeページ      | 
| /     | ログイン後homeページ      | 
| /games/new       | ゲーム作成ページ        | 
| /games/[:id]         | ゲーム詳細ページ          | 
| /games/[:id]/edit       | ゲーム編集ページ       | 
| /games/[:id]?title=[:game_title]    | ゲーム会場ページ     | 
| /login    | ログインページ     | 
| /withdrawal    | 退会完了ページ     | 

### バックエンド
| HTTPメソッド | PATH | 説明 |
|:-----------|:------------|:------------|
| POST       | /api/v1/users        | ユーザーの登録         |
| DELETE     | /api/v1/users      | ユーザーの退会       |
| GET       |   /api/v1/users/[:user_id]/games      | ユーザーが作成したゲームを取得         |
| POST         | /api/v1/games          | ゲーム登録           |
| GET       | /api/v1/games/[:game_id]       | ゲーム詳細取得       |
| PATCH    | /api/v1/games/[:game_id]     | ゲーム更新      |
| DELETE    | /api/v1/games/[:game_id]     | ゲーム削除      |

以上です。よろしくおねがいします。

**Comment by kfukai23** [comment]
LGTM🌻
